<?php
/**
 * Novalnet payment extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Novalnet End User License Agreement
 * that is bundled with this package in the file LICENSE.txt
 *
 * DISCLAIMER
 *
 * If you wish to customize Novalnet payment extension for your needs,
 * please contact technic@novalnet.de for more information.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG
 * @license    https://www.novalnet.de/payment-plugins/kostenlos/lizenz
 */
?>
<!-- Remove payment token popup -->
<div id="remove-nntoken-modal" style="display:none">
    <span><?= /* @noEscape */ __('Are you sure you want to remove these account details?') ?></span>
</div>
<div id="remove-nntoken-cc-modal" style="display:none">
    <span><?= /* @noEscape */ __('Are you sure you want to remove these Credit Card details?') ?></span>
</div>
