<?php
/**
 * Novalnet payment extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Novalnet End User License Agreement
 * that is bundled with this package in the file LICENSE.txt
 *
 * DISCLAIMER
 *
 * If you wish to customize Novalnet payment extension for your needs,
 * please contact technic@novalnet.de for more information.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG
 * @license    https://www.novalnet.de/payment-plugins/kostenlos/lizenz
 */
?>
<br>
<div id="novalnet_applepay_minicartdiv" style="display:none" >
    <div id="novalnet_applepay_minicartbtn" class="apple-pay-button" ></div>
</div>
<script>
    require(['jquery', 'domReady!', 'Novalnet_Payment/js/novalnetApplePayHelper', 'Magento_Customer/js/customer-data'],
       function($, domReady, nnApplePayHelperJs, customerData) {

        loadMinicart();

        function loadMinicart() {
              nnApplePayHelperJs.getCartItems(function(minicartQuote) {
                  nnApplePayHelperJs.initMiniCart(minicartQuote);
              });
        };

        var cart = customerData.get('cart');
            cart.subscribe(function() {
                setTimeout(function() {
                    loadMinicart()
                },500);
            });
    });
</script>
