<?php
/**
 * Novalnet payment extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Novalnet End User License Agreement
 * that is bundled with this package in the file LICENSE.txt
 *
 * DISCLAIMER
 *
 * If you wish to customize Novalnet payment extension for your needs,
 * please contact technic@novalnet.de for more information.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG
 * @license    https://www.novalnet.de/payment-plugins/kostenlos/lizenz
 */

$isEnabled = $block->isPageEnabledForExpressCheckout('shopping_cart_page');
?>
<?php if ($isEnabled['novalnetApplepay']): ?>
    <div id="novalnet_applepay_cartdiv" style="display:none" >
        <div id="nn_applepay_cart" ></div>
        <br>
    </div>
<?php endif; ?>

<?php if ($isEnabled['novalnetGooglepay']): ?>
    <div id="novalnet_googlepay_cartdiv" style="display:none" >
        <div id="nn_googlepay_cart"  ></div>
        <br>
    </div>
<?php endif; ?>

<?php if ($isEnabled['novalnetGooglepay'] || $isEnabled['novalnetApplepay']): ?>
    <script>
        require(['jquery', 'domReady!', 'Novalnet_Payment/js/novalnetCheckoutHelper'],
             function($, domReady, nnCheckoutHelper) {
                nnCheckoutHelper.getCartItems(function(cartPagequote) {
                  nnCheckoutHelper.initCartPage(cartPagequote);
                });
            });
    </script>
<?php endif; ?>

