<?php
/**
 * Novalnet payment extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Novalnet End User License Agreement
 * that is bundled with this package in the file LICENSE.txt
 *
 * DISCLAIMER
 *
 * If you wish to customize Novalnet payment extension for your needs,
 * please contact technic@novalnet.de for more information.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG
 * @license    https://www.novalnet.de/payment-plugins/kostenlos/lizenz
 */
?>
<?php if ($block->activateGlobalConfiguration()): ?>
    <style type="text/css">div.novalnet-payment-section .section-config{display:none;}</style>
    <div class="novalnet_payment-active-notice deprecated-message">
        <div class="comment">
            <?= /* @noEscape */ __('Configure the valid Product Activation Key and Payment Access key to activate the payment types under <b>Configuration</b> settings.') ?>
        </div>
    </div>
<?php else: ?>
    <style type="text/css">tr[id$="novalnet_global_nn_payment_methods_activate_novalnet_payment_notice"]{display:none;}</style>
<?php endif;?>
