<?php
/**
 * Novalnet payment extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Novalnet End User License Agreement
 * that is bundled with this package in the file LICENSE.txt
 *
 * DISCLAIMER
 *
 * If you wish to customize Novalnet payment extension for your needs,
 * please contact technic@novalnet.de for more information.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG
 * @license    https://www.novalnet.de/payment-plugins/kostenlos/lizenz
 */

/**
 * @var $block Novalnet\Payment\Block\Method\Form\Cc
 */
$paymentMethodcode = $block->escapeHtml($block->getMethodCode());
$formData = [
    'code' => $paymentMethodcode,
    'inlineForm' => $block->isInlineForm(),
    'iframeParams' => $block->getCcIframeParams(),
    'config' => $block->getConfig($paymentMethodcode),
    'billing' =>$block->novalnetHelper()->getBillingAddress(),
    'shipping' =>$block->novalnetHelper()->getShippingAddress(),
    'amount' => $block->novalnetHelper()->getAmount()
];
$serializedFormData = $block->jsonHelper()->jsonEncode($formData);
?>
<fieldset class="admin__fieldset payment-method"
          id="payment_form_<?= /* @noEscape */ $paymentMethodcode; ?>"
          style="display:none"
          data-mage-init='{"novalnetCcFormJs":<?= /* @noEscape */ $serializedFormData; ?>}'>
    <div class="admin__field">
        <!-- Payment logo -->
        <?php if (!empty($block->getCreditCardLogos($paymentMethodcode))): ?>
            <?php foreach ($block->getCreditCardLogos($paymentMethodcode) as $key => $value): ?>
                    <img src="<?= /* @noEscape */ $value['src']; ?>"
                         alt="<?= /* @noEscape */ $value['title']; ?>"
                         title="<?= /* @noEscape */ $value['title']; ?>" />
            <?php endforeach; ?>
        <?php endif; ?>
        <!-- PSD2 description -->
        <ul class="row" style="list-style-type: none;">
            <li style="float:left"><?= $block->escapeHtml(__('More security with the new Payment Policy (PSD2) Info')); ?></li>
            <li style="float:left">
                <div class="tooltip">
                    <span class="help">
                        <span></span>
                    </span>
                    <div class="tooltip-content">
                        <?= $block->escapeHtml(__("European card issuing banks often requires a password or some other form of authentication (EU Payment Services Directive 'PSD2') for secure payment. If the payment is not successful, you can try again. If you have any further questions, please contact your bank.")); ?>
                    </div>
                </div>
            </li>
        </ul>
        <!-- Test mode notification -->
        <?php if ($block->getTestMode($paymentMethodcode)): ?>
            <div class="nn-mode">
                <div class="nn-test-drive"><?= $block->escapeHtml(__('TestMode')); ?></div>
            </div>
        <?php endif; ?>
        <iframe width="100%"
                frameborder="0"
                border="0"
                id="novalnet_iframe">
        </iframe>
        <!-- Payment description -->
        <p>
            <?= $block->escapeHtml(__('The amount will be debited from your credit/debit card')); ?><br>
        </p>
    </div>
    <!-- Form hidden elements -->
    <div class="no-display">
        <input type="hidden"
               id="novalnetCc_pan_hash"
               name="payment[novalnetCc_pan_hash]"/>
        <input type="hidden"
               id="novalnetCc_unique_id"
               name="payment[novalnetCc_unique_id]"/>
        <input type="hidden"
               id="nn_chk_button"
               name="nn_chk_button"/>
        <input type="hidden"
               id="nn_cc_standard_style_label"
               value="<?= /* @noEscape */($block->getStyleConfig('standard_style_label')); ?>" />
        <input type="hidden"
               id="nn_cc_standard_style_input"
               value="<?= /* @noEscape */($block->getStyleConfig('standard_style_input')); ?>" />
        <input type="hidden"
               id="nn_cc_standard_style_css"
               value="<?= /* @noEscape */($block->getStyleConfig('standard_style_css')); ?>" />
        <input type="hidden"
               id="nn_cc_validate_text"
               value="<?= $block->escapeHtml(__('Your credit card details are invalid')); ?>" />
        <input type="hidden"
               id="nn_cc_holder_label"
               value="<?= $block->escapeHtml(__('Card holder name')); ?>" />
        <input type="hidden"
               id="nn_cc_holder_field"
               value="<?= $block->escapeHtml(__('Name on card')); ?>" />
        <input type="hidden"
               id="nn_cc_number_label"
               value="<?= $block->escapeHtml(__('Card number')); ?>" />
        <input type="hidden"
               id="nn_cc_number_field"
               value="<?= $block->escapeHtml(__('XXXX XXXX XXXX XXXX')); ?>" />
        <input type="hidden"
               id="nn_cc_date_label"
               value="<?= $block->escapeHtml(__('Expiry date')); ?>" />
        <input type="hidden"
               id="nn_cc_date_field"
               value="<?= $block->escapeHtml(__('MM / YYYY')); ?>" />
        <input type="hidden"
               id="nn_cc_cvc_label"
               value="<?= $block->escapeHtml(__('CVC/CVV/CID')); ?>" />
        <input type="hidden"
               id="nn_cc_cvc_field"
               value="<?= $block->escapeHtml(__('XXX')); ?>" />
        <input type="hidden"
               id="nn_cc_cvc_hint"
               value="<?= $block->escapeHtml(__('what is this?')); ?>" />
    </div>
</fieldset>
