<?php
/**
 * Novalnet payment extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Novalnet End User License Agreement
 * that is bundled with this package in the file LICENSE.txt
 *
 * DISCLAIMER
 *
 * If you wish to customize Novalnet payment extension for your needs,
 * please contact technic@novalnet.de for more information.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG
 * @license    https://www.novalnet.de/payment-plugins/kostenlos/lizenz
 */

/**
 * @var $block \Novalnet\Payment\Block\Onepage\Success\Message
 */
$cpAdditionalData = $block->getCpAdditionalData();
?>
<?php if (!empty($cpAdditionalData)): ?>
    <?php
        $CheckoutJsUrl = !empty($cpAdditionalData['NnCheckoutJs']) ? $cpAdditionalData['NnCheckoutJs'] : '';
        $CheckoutToken = !empty($cpAdditionalData['NnCheckoutToken']) ? $cpAdditionalData['NnCheckoutToken'] : '';
    ?>
    <style type="text/css">
        #bz-checkout-modal { position: fixed !important; }
    </style>
    <script src="<?= /* @noEscape */ $CheckoutJsUrl ?>" class="bz-checkout"
        data-token="<?= /* @noEscape */ $CheckoutToken ?>">
    </script>
    <a href="javascript:bzCheckout.display();"><?= /* @noEscape */ __('Pay now with Barzahlen'); ?></a>
<?php endif;?>
