<?php
/**
 * Novalnet payment extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Novalnet End User License Agreement
 * that is bundled with this package in the file LICENSE.txt
 *
 * DISCLAIMER
 *
 * If you wish to customize Novalnet payment extension for your needs,
 * please contact technic@novalnet.de for more information.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG
 * @license    https://www.novalnet.de/payment-plugins/kostenlos/lizenz
 */

/**
 * @var \Novalnet\Payments\Block\Info\SepaInstalment
 */
$info = $block->getInfo();
$order = $info->getOrder();
$transactionId = $block->getAdditionalData('NnTid') ? $block->getAdditionalData('NnTid') : $info->getLastTransId();
$parentTid = $block->getAdditionalData('NnparentTid') ? $block->getAdditionalData('NnparentTid') : $info->getLastTransId();
$paymentStatus = $block->novalnetHelper()->getStatus($block->getAdditionalData('NnStatus'), $order);
?>
<?php if ($info): ?>
    <?php if ($block->getAdditionalData('NnTestMode')): ?>
        <div style="color:white;font-weight:bold;background:red;padding:5px 10px;text-align:center;font-size:15px">
            <?= /* @noEscape */ __('Test order') ?>
        </div>
    <?php endif; ?>
    <?= $block->escapeHtml($block->getMethod()->getTitle()) ?><br>

    <?php if ($transactionId): ?>
        <?= /* @noEscape */ __('Novalnet Transaction ID: '). $transactionId ?><br><br>
    <?php endif; ?>

    <?php if ($paymentStatus == 'PENDING'): ?>
        <?= /* @noEscape */ __('Your order is under verification and we will soon update you with the order status. Please note that this may take upto 24 hours.') ?><br><br>
    <?php endif; ?>

    <?php if ($block->getAdditionalData('ApiProcess') == 'capture'): ?>
        <?= /* @noEscape */ __(
            'The transaction has been confirmed on %1',
            $block->getAdditionalData('ApiProcessedAt')
        ) ?><br><br>
    <?php elseif ($block->getAdditionalData('ApiProcess') == 'void'): ?>
        <?= /* @noEscape */ __(
            'The transaction has been canceled on %1',
            $block->getAdditionalData('ApiProcessedAt')
        ) ?><br><br>
    <?php endif; ?>

    <?php if (!empty($block->getAdditionalData('Nninstalmetexc'))): ?>
        <?php if (!empty($block->getAdditionalData('Nninstalmentnew'))): ?>
            <?php foreach ($block->getAdditionalData('Nninstalmentnew') as $key => $value): ?>
                <br>
                <?php
                $message = __('A new instalment has been received for the Transaction ID: %1.
                The new instalment Transaction ID is: %2 %3 on %4 ',
                    str_replace('-capture','',  $parentTid),
                    $value['Nninstalmentnewtid'],
                    !empty($value['NninstalmentnewAmount']) ? __('with the amount %1', $value['NninstalmentnewAmount']) : '',
                    $value['Nninstalmentnewtime'],
                );
                ?><br>
                <?= /* @noEscape */ $message ?><br>
            <?php endforeach; ?><br>
        <?php endif; ?>
    <?php endif; ?>

    <!--Instalment Cancel (cycles info) -->
    <?php if ($block->getAdditionalData('InstalmentCancel')): ?>
        <br>
        <?php if ($block->getAdditionalData('CANCEL_ALL_CYCLES')): ?>
            <?= /* @noEscape */ __(
                'Instalment has been cancelled for the TID: %1',
                str_replace('-capture','',  $parentTid)
            ) ?>
        <?php endif; ?>
        <?php if ($block->getAdditionalData('CANCEL_REMAINING_CYCLES')): ?>
            <?= /* @noEscape */ __('Instalment has been stopped for the TID: %1' , 
            str_replace('-capture','',  $parentTid)
            ) ?><?php endif; ?><br>
    <?php endif; ?>

    <?php if ($block->getAdditionalData('NnRefunded')): ?>
        <?php foreach ($block->getAdditionalData('NnRefunded') as $key => $value): ?>
            <?php if (!empty($value['reftid']) && preg_match("/-refund/i", $value['reftid'])): ?>
                <?= /* @noEscape */ __(
                    'Refund has been initiated for the TID:%1 with the amount %2',
                    $block->novalnetHelper()->makeValidNumber($value['reqtid']),
                    $value['refamount']
                ) ?><br>
            <?php else: ?>
                <?= /* @noEscape */ __(
                    'Refund has been initiated for the TID: %1 with the amount %2. New TID:%3 for the refunded amount',
                    $block->novalnetHelper()->makeValidNumber($value['reqtid']),
                    $value['refamount'],
                    $block->novalnetHelper()->makeValidNumber($value['reftid'])
                ) ?><br>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>

    <?php if ($block->getAdditionalData('NnComments')): ?>
        <?= /* @noEscape */ $block->getAdditionalData('NnComments') ?>
    <?php endif; ?>
<?php else: ?>
    <?= /* @noEscape */ __('Error in getting payment method') ?>
<?php endif; ?>
